#!/usr/sbin/env python
# -*- coding: utf-8 -*-

import ctypes

#--- CTYPES SHORTCUTS -------------------------------------------------------------------------------

# functions
cStruct = ctypes.Structure
cUnion = ctypes.Union
cByref = ctypes.byref
cPointer = ctypes.pointer 
cSizeof = ctypes.sizeof
cCreateStr = ctypes.create_string_buffer

# fabriques
cPointerType = ctypes.POINTER 
cFuncType = ctypes.CFUNCTYPE 

#--- CTYPE TYPES -------------------------------------------------------------------------------------------

BOOL = ctypes.c_int # define BOOL int
BYTE = ctypes.c_ubyte # typedef unsigned char BYTE;

CHAR = ctypes.c_char
UCHAR = ctypes.c_ubyte

USHORT = ctypes.c_ushort # typedef unsigned short USHORT;

INT = ctypes.c_int
UINT = ctypes.c_uint
SHORTINT = ctypes.c_int

LONG = ctypes.c_long # typedef int LONG;
ULONG = ctypes.c_ulong
ULONGLONG = ctypes.c_ulonglong

FLOAT = ctypes.c_float

WORD = ctypes.c_ushort # typedef unsigned short WORD;
DWORD = ctypes.c_ulong # typedef unsigned int DWORD;

HANDLE = ctypes.c_int
HWND = ctypes.c_uint

PCHAR = ctypes.c_char_p
PVOID = ctypes.c_void_p

HDC = ctypes.c_int # typedef void *HDC;

#--- DEFINES --------------------------------------------------------------------------------------------------

MAX_DEVICE_NAME_LEN = 127 # max device name string length (exclude '\0')
MAX_DESCRIPTION_LEN = 127 # max (exclude '\0')
MAX_SERIAL_NUM = 127 # (exclude '\0')
MAX_USERNAME_LEN = 63 # max user name string length (exclude '\0')
MAX_PWD_LEN = 15 # max password string length (exclude '\0')
MAX_LOCATION_LEN = 127 # file location url length
MAX_FILENAME_LEN = 127 # file name string length (exclude '\0')
MAX_HOST_NAME_LEN = 127 # host name string length (exclude '\0')
MAX_DOMAIN_NAME = 127 # domain name string length (exclude '\0')
MAX_OSDTXT_LEN = 127 # 
MAX_WIFISSID_LEN = 32
WIFI_WEP_MAX_KEY_COUNT = 4
MAX_LOG_INFO_LEN = 255 # log info string length (exclude '\0')
MAX_SSID_LEN = 127 # Service Set Identifier length (exclude '\0')
MAX_WIFIKEY_LEN = 127
IPADRRESS_LEN = 16 #< IPv4
IPV6ADDRESS_LEN = 128 #< IPv6
MAX_IPFILTER_NUM = 8 #< filter num
MAC_LEN = 23 #< mac address length
MAX_USER_NUM = 16 #< maxium user acount
MAX_MD_AREAS = 4 #< maxium motion detection areas
MAX_PRIVACYMASK_AREAS = 4 #< maxium privacy mask areas

MAX_DAYS = 7 #<
MAX_TIMESEGMENTS = 6 #<

MAX_IPC_CHN_NUM = 1 #<
MAX_INFO_LEN = 255 #<

MAX_IOIN_NUM = 64 #<
MAX_IOOUT_NUM = 64 #<

MAX_TCPALARM_NAME = 63
MAX_TCPALARMIP_LEN = 127

MAX_EMAILADDR_LEN = 63 # email address string length (exclude '\0')
MAX_MAIL_RECEIVERS = 4 #< max
MAX_EMAILSRV_NUM = 2

MAX_ALARMIN_NAME = 31
MAX_NET_PROTO_NUM = 32

MAX_WIFISSID_LEN = 32
MAX_WIFIWEP64KEY_LEN = 64
MAX_WIFIWEP128KEY_LEN = 128
MAX_WIFIWPAKEY_LEN = 63

NETIFACE_COUNT = 2 #< 0:ethernet, 1:wifi
MAX_WIFISSID_LEN = 32
IPADDRESS_LEN = 16 #< IPv4
MAX_WIFIWEP64KEY_LEN = 64
MAX_WIFIWEP128KEY_LEN = 128
MAX_WIFIWPAKEY_LEN = 63



CMD_GET_NTP = 0 #< Get NtpCfg_t
CMD_SET_NTP = 1 #< Set NtpCfg_t
CMD_GET_DEVICEINFO = 2 #< Get DeviceInfo_t
CMD_GET_DEVICESTATUS = 3 #< Get DeviceStatus_t
CMD_GET_TIME = 4 #< Get TimeInfo_t
CMD_SET_TIME = 5 #< Set TimeInfo_t
CMD_GET_FTPCFG = 6 #< Get FTPCfg_t
CMD_SET_FTPCFG = 7 #< Set FTPCfg_t
CMD_GET_MJPEGCFG = 8 #< Get ImgCfg_t
CMD_SET_MJPEGCFG = 9 #< Set ImgCfg_t
CMD_GET_CAMERACFG = 10 #< Get CameraCfg_t
CMD_SET_CAMERACFG = 11 #< Set CameraCfg_t
CMD_SET_PRIVACYMASK = 12 #< Get PrivacyMask_t
CMD_GET_MOTIONDETECT = 13 #< Get MotionDetection_t
CMD_SET_MOTIONDETECT = 14 #< Set MotionDetection_t
CMD_GET_CAMERATAMPER = 15 #< Get CameraTamper_t
CMD_SET_CAMERATAMPER = 16 #< Set CameraTamper_t
CMD_GET_SNAP_CFG = 17 #< Get NET_SNAP_CFG
CMD_SET_SNAP_CFG = 18 #< Set NET_SNAP_CFG
CMD_GET_WIFI = 19 #< Get WIFICfg_t
CMD_SET_WIFI = 20 #< Set WIFICfg_t
CMD_GET_IOOUTCFG = 21 #< Get
CMD_SET_IOOUTCFG = 22 #< Set
CMD_GET_SMTPCFG = 23 #< Get MailCfg_t
CMD_SET_SMTPCFG = 24 #< Set MailCfg_t
CMD_GET_DDNSCFG = 25 #< Get DDNSCfg_t
CMD_SET_DDNSCFG = 26 #< Set DDNSCfg_t
CMD_GET_SERIALPORTCFG = 27 #<
CMD_SET_SERIALPORTCFG = 28 #<
CMD_GET_VIDEOCODECCFG = 29 #< Get VideoCodecCfg_t
CMD_SET_VIDEOCODECCFG = 30 #< Set VideoCodecCfg_t
CMD_GET_AUDIOCODECCFG = 31 #< Get AudioCfg_t
CMD_SET_AUDIOCODECCFG = 32 #< Set AudioCfg_t
CMD_GET_IPFILTERCFG = 33 #< Get IPFilter_t
CMD_SET_IPFILTERCFG = 34 #< Set IPFilter_t
CMD_GET_PTZPROTOCOL = 35 #<
CMD_GET_VIDEOEFFECT = 36 #<
CMD_SET_VIDEOEFFECT = 37 #<
CMD_GET_SERVERPORTS = 38 #< Set ServerPorts_t
CMD_SET_SERVERPORTS = 39 #< Set ServerPorts_t
CMD_GET_DSTCFG = 40 #<
CMD_SET_DSTCFG = 41 #<
CMD_GET_STORAGEDEVINFO = 42 #<
CMD_GET_MULTICAST_CFG = 43 #<
CMD_SET_MULTICAST_CFG = 44 #<
CMD_GET_OSDCFG = 45 #< Get OSDCfg_t
CMD_SET_OSDCFG = 46 #< Set OSDCfg_t
CMD_GET_USERLIST = 47 #< Get UserList_t
CMD_SET_USERLIST = 48 #< Set UserList_t
CMD_GET_LOGCFG = 49 #<
CMD_SET_LOGCFG = 50 #<
CMD_GET_REC_PACKET_CFG = 51 #<
CMD_SET_REC_PACKET_CFG = 52 #<
CMD_GET_RECORD_CFG = 53 #<
CMD_SET_RECORD_CFG = 54 #<
CMD_GET_NETCFG = 55 #< Get
CMD_SET_NETCFG = 56 #< Set
CMD_GET_VIDEOGLOBALCFG = 57 #< Get VideoGlobalCfg_t
CMD_SET_VIDEOGLOBALCFG = 58 #< Set VideoGlobalCfg_t
CMD_GET_VIDEOOUTPUTCFG = 59 #< Set VideoOutputCfg_t
CMD_SET_VIDEOOUTPUTCFG = 60 #< Set VideoOutputCfg_t
CMD_GET_VSPROTOCAL = 61 #<
CMD_SET_VSPROTOCAL = 62 #<
CMD_GET_UPLOAD = 63 #< Get NET_UPLOAD_CFG
CMD_SET_UPLOAD = 64 #< Set NET_UPLOAD_CFG
CMD_GET_IO = 65 #< Get NET_ALARM_IO_CFG
CMD_SET_IO = 66 #< Set NET_ALARM_IO_CFG
CMD_GET_BOOT = 67 #< Get NET_ALARM_BOOT_CFG
CMD_SET_BOOT = 68 #< Set NET_ALARM_BOOT_CFG
CMD_GET_NETBROKEN = 69 #< Get NET_ALARM_NETBROKEN_CFG
CMD_SET_NETBROKEN = 70 #< Set NET_ALARM_NETBROKEN_CFG

#--- TFCPalySDK ------------------------------------------------------------

DECODE_NORMAIL = 0
DECODE_KEY_FRAME = 1
DECODE_NONE = 2
STREAM_REALTIME = 0
STREAM_FILE = 1
DISPLAY_NORMAL = 2
DISPLAY_QUARTER = 3
DISPLAY_MODIFY_RESOLUTION = 4
WH_RATIO_NORMAL = 0
WH_RATIO_4_3 = 1
WH_RATIO_16_9 = 2
BUF_VIDEO_SRC = 0
BUF_AUDIO_SRC = 1
BUF_VIDEO_RENDER = 2
BUF_AUDIO_RENDER = 3
MAX_VIDEOPLAYER_NUM = 36
MAX_RECORDER_NUM = 36
MAX_OSD_TXT_LEN = 32

PLAY_FPSTART = 0L
PLAY_FPCURRENT = 1L
PLAY_FPEND = 2L
PLAY_PCPLAY = 0L
PLAY_PCPAUSE = 1L
PLAY_PCNORMAL = 2L
PLAY_PCBACK = 3L

BY_FRAMETIME = 0
BY_FRAMENUM = 1

FRAMETYPE_NONE = 0L
FRAMETYPE_I = 0x00000001L
FRAMETYPE_P = 0x00000002L
FRAMETYPE_VIDEO = 0x00000003L
FRAMETYPE_A = 0x00000004L
FRAMETYPE_JPEG = 0x00000008L
FRAMETYPE_UPGRADE = 0x00000009L
FRAMETYPE_COVER = 0x0000000AL
FRAMETYPE_END = 0x000000FFL

PLAY_NOERROR = 0x00000000L
PLAY_ERR_SRC_IO = 0x00000002L
PLAY_ERR_SRC_REMOTE = 0x00000003L
PLAY_ERR_SRC_AVDATA = 0x00000004L
PLAY_ERR_SRC_MEMORY = 0x00000005L
PLAY_ERR_SRC_PARAMETER = 0x00000006L
PLAY_ERR_SRC_THREAD = 0x00000007L
PLAY_ERR_SRC_OTHER = 0x000000F0L
PLAY_ERR_SRC_RESERVED = 0x000000FEL
PLAY_ERR_SRC_UNKNOWN = 0x000000FFL
PLAY_ERR_UNKNOWN = 0x80FF0000L
PLAY_ERR_UNKNOWN_ALL = 0x80FF0000L
PLAY_ERR_IO_PLAYING = 0x80020001L
PLAY_ERR_IO_NOTPLAYING = 0x80020002L
PLAY_ERR_IO_SAVING = 0x80020003L
PLAY_ERR_IO_NOTSAVEING = 0x80020004L
PLAY_ERR_IO_OPENFILE_FAILED = 0x80020005L
PLAY_ERR_IO_FILELEN_ERROR = 0x80020006L
PLAY_ERR_IO_NOSPACE = 0x80020007L
PLAY_ERR_IO_ALARMEMPTY = 0x80020008L
PLAY_ERR_IO_READ_FILE_FAILED = 0x80020009L
PLAY_ERR_IO_TYPE_NOT_SUPPORT = 0x8002000AL
PLAY_ERR_IO_OPENDECODER_FAILED = 0x8002000BL
PLAY_ERR_IO_FILEEXIST = 0x8002000CL
PLAY_ERR_IO_READHEADER_FAILED = 0x8002000DL
PLAY_ERR_IO_OFFSETTOOLONG = 0x8002000EL
PLAY_ERR_IO_OFFSETTOOLSHORT = 0x8002000FL
PLAY_ERR_IO_NOTCLIPALL = 0x80020010L
PLAY_ERR_IO_TIMEFMTINCORRECT = 0x80020011L
PLAY_ERR_IO_FILEOPENED = 0x80020012L
PLAY_ERR_IO_FILENAMEINCORRECT = 0x80020013L
PLAY_ERR_IO_FILENOTOPENED = 0x80020014L
PLAY_ERR_IO_CREATETIMERFAILED = 0x80020015L
PLAY_ERR_IO_GETFULLPATH_FAILED = 0x80020017L
PLAY_ERR_IO_SPEEDNOTSUPPORT = 0x80020019L
PLAY_ERR_IO_GETFILELIST_FAILED = 0x8002001AL
PLAY_ERR_IO_NOFILEINLIST = 0x8002001BL
PLAY_ERR_IO_FILENOTMODIFY = 0x8002001CL
PLAY_ERR_AVDATA_NOTRIGHT = 0x80040001L
PLAY_ERR_AVDATA_NOFRAME = 0x80040002L
PLAY_ERR_AVDATA_NOIFRAME = 0x80040003L
PLAY_ERR_MEM_OUT = 0x80050001L
PLAY_ERR_MEM_OPENDECODER_FAILED = 0x80050002L
PLAY_ERR_MEM_OPERATION_FAILED = 0x80050003L
PLAY_ERR_MEM_CREATEEVENT_FAILED = 0x80050004L
PLAY_ERR_PAR_PARAMETER = 0x80060000L
PLAY_ERR_THREAD_CREATE_FAILED = 0x80070001L
PLAY_ERR_THREAD_CTIMER_FAILED = 0x80070002L
PLAY_ERR_OTHER_NORIGHT = 0x80F00001L
PLAY_ERR_OTHER_NOTSUPPORT = 0x80F00002L
PLAY_ERR_OTHER_TASKGOING = 0x80F00003L
PLAY_ERR_OTHER_TASKNOTGO = 0x80F00004L
PLAY_ERR_OTHER_BEGDECODE_FAILED = 0x80F00005L
PLAY_ERR_OTHER_PROT_NOTSUPPORTED = 0x80F00006L
PLAY_ERR_OTHER_NOTINIT = 0x80F00007L
PLAY_ERR_OTHER_UNKNOWN_DEVICE = 0x80F00008L
PLAY_ERR_OTHER_NOSUBCLASS_FUNCTION = 0x80F00009L
PLAY_ERR_OTHER_NOTFIND = 0x80F0000AL
PLAY_ERR_OTHER_ENDALREADY = 0x80F0000BL
PLAY_ERR_OTHER_NONEED = 0x80F0000CL
PLAY_ERR_OTHER_INITFAILED = 0x80F0000DL
PLAY_ERR_OTHER_NOT_IMPLEMENT = 0x80F0000EL
PLAY_ERR_OTHER_NOT_EXIST = 0x80F0000FL

